/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain.jpetstore.tables;


import cn.emac.demo.petstore.domain.jpetstore.Jpetstore;
import cn.emac.demo.petstore.domain.jpetstore.Keys;
import cn.emac.demo.petstore.domain.jpetstore.tables.records.BannerdataRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Banner Data
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bannerdata extends TableImpl<BannerdataRecord> {

	private static final long serialVersionUID = 735604249;

	/**
	 * The reference instance of <code>jpetstore.bannerdata</code>
	 */
	public static final Bannerdata BANNERDATA = new Bannerdata();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BannerdataRecord> getRecordType() {
		return BannerdataRecord.class;
	}

	/**
	 * The column <code>jpetstore.bannerdata.favcategory</code>.
	 */
	public final TableField<BannerdataRecord, String> FAVCATEGORY = createField("favcategory", org.jooq.impl.SQLDataType.VARCHAR.length(80).nullable(false), this, "");

	/**
	 * The column <code>jpetstore.bannerdata.bannername</code>.
	 */
	public final TableField<BannerdataRecord, String> BANNERNAME = createField("bannername", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>jpetstore.bannerdata</code> table reference
	 */
	public Bannerdata() {
		this("bannerdata", null);
	}

	/**
	 * Create an aliased <code>jpetstore.bannerdata</code> table reference
	 */
	public Bannerdata(String alias) {
		this(alias, BANNERDATA);
	}

	private Bannerdata(String alias, Table<BannerdataRecord> aliased) {
		this(alias, aliased, null);
	}

	private Bannerdata(String alias, Table<BannerdataRecord> aliased, Field<?>[] parameters) {
		super(alias, Jpetstore.JPETSTORE, aliased, parameters, "Banner Data");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<BannerdataRecord> getPrimaryKey() {
		return Keys.KEY_BANNERDATA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<BannerdataRecord>> getKeys() {
		return Arrays.<UniqueKey<BannerdataRecord>>asList(Keys.KEY_BANNERDATA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Bannerdata as(String alias) {
		return new Bannerdata(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Bannerdata rename(String name) {
		return new Bannerdata(name, null);
	}
}
