/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain.jpetstore.tables;


import cn.emac.demo.petstore.domain.jpetstore.Jpetstore;
import cn.emac.demo.petstore.domain.jpetstore.Keys;
import cn.emac.demo.petstore.domain.jpetstore.tables.records.CategoryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Categorias
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Category extends TableImpl<CategoryRecord> {

	private static final long serialVersionUID = -792221870;

	/**
	 * The reference instance of <code>jpetstore.category</code>
	 */
	public static final Category CATEGORY = new Category();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CategoryRecord> getRecordType() {
		return CategoryRecord.class;
	}

	/**
	 * The column <code>jpetstore.category.catid</code>.
	 */
	public final TableField<CategoryRecord, String> CATID = createField("catid", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>jpetstore.category.name</code>.
	 */
	public final TableField<CategoryRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(80), this, "");

	/**
	 * The column <code>jpetstore.category.descn</code>.
	 */
	public final TableField<CategoryRecord, String> DESCN = createField("descn", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>jpetstore.category</code> table reference
	 */
	public Category() {
		this("category", null);
	}

	/**
	 * Create an aliased <code>jpetstore.category</code> table reference
	 */
	public Category(String alias) {
		this(alias, CATEGORY);
	}

	private Category(String alias, Table<CategoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Category(String alias, Table<CategoryRecord> aliased, Field<?>[] parameters) {
		super(alias, Jpetstore.JPETSTORE, aliased, parameters, "Categorias");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CategoryRecord> getPrimaryKey() {
		return Keys.KEY_CATEGORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CategoryRecord>> getKeys() {
		return Arrays.<UniqueKey<CategoryRecord>>asList(Keys.KEY_CATEGORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Category as(String alias) {
		return new Category(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Category rename(String name) {
		return new Category(name, null);
	}
}
