/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain.jpetstore.tables;


import cn.emac.demo.petstore.domain.jpetstore.Jpetstore;
import cn.emac.demo.petstore.domain.jpetstore.Keys;
import cn.emac.demo.petstore.domain.jpetstore.tables.records.SignonRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Cadastro de usuários
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Signon extends TableImpl<SignonRecord> {

	private static final long serialVersionUID = -1708165641;

	/**
	 * The reference instance of <code>jpetstore.signon</code>
	 */
	public static final Signon SIGNON = new Signon();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SignonRecord> getRecordType() {
		return SignonRecord.class;
	}

	/**
	 * The column <code>jpetstore.signon.username</code>.
	 */
	public final TableField<SignonRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * The column <code>jpetstore.signon.password</code>.
	 */
	public final TableField<SignonRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * Create a <code>jpetstore.signon</code> table reference
	 */
	public Signon() {
		this("signon", null);
	}

	/**
	 * Create an aliased <code>jpetstore.signon</code> table reference
	 */
	public Signon(String alias) {
		this(alias, SIGNON);
	}

	private Signon(String alias, Table<SignonRecord> aliased) {
		this(alias, aliased, null);
	}

	private Signon(String alias, Table<SignonRecord> aliased, Field<?>[] parameters) {
		super(alias, Jpetstore.JPETSTORE, aliased, parameters, "Cadastro de usuários");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SignonRecord> getPrimaryKey() {
		return Keys.KEY_SIGNON_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SignonRecord>> getKeys() {
		return Arrays.<UniqueKey<SignonRecord>>asList(Keys.KEY_SIGNON_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Signon as(String alias) {
		return new Signon(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Signon rename(String name) {
		return new Signon(name, null);
	}
}
