/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain.tables;


import cn.emac.demo.petstore.domain.Jpetstore;
import cn.emac.demo.petstore.domain.Keys;
import cn.emac.demo.petstore.domain.tables.records.ProductRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * Categorias
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product extends TableImpl<ProductRecord> {

	private static final long serialVersionUID = 1566127591;

	/**
	 * The reference instance of <code>jpetstore.product</code>
	 */
	public static final Product PRODUCT = new Product();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ProductRecord> getRecordType() {
		return ProductRecord.class;
	}

	/**
	 * The column <code>jpetstore.product.productid</code>.
	 */
	public final TableField<ProductRecord, String> PRODUCTID = createField("productid", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>jpetstore.product.category</code>.
	 */
	public final TableField<ProductRecord, String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>jpetstore.product.name</code>.
	 */
	public final TableField<ProductRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(80), this, "");

	/**
	 * The column <code>jpetstore.product.descn</code>.
	 */
	public final TableField<ProductRecord, String> DESCN = createField("descn", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>jpetstore.product</code> table reference
	 */
	public Product() {
		this("product", null);
	}

	/**
	 * Create an aliased <code>jpetstore.product</code> table reference
	 */
	public Product(String alias) {
		this(alias, PRODUCT);
	}

	private Product(String alias, Table<ProductRecord> aliased) {
		this(alias, aliased, null);
	}

	private Product(String alias, Table<ProductRecord> aliased, Field<?>[] parameters) {
		super(alias, Jpetstore.JPETSTORE, aliased, parameters, "Categorias");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ProductRecord> getPrimaryKey() {
		return Keys.KEY_PRODUCT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ProductRecord>> getKeys() {
		return Arrays.<UniqueKey<ProductRecord>>asList(Keys.KEY_PRODUCT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ProductRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ProductRecord, ?>>asList(Keys.PRODUCT_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Product as(String alias) {
		return new Product(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Product rename(String name) {
		return new Product(name, null);
	}
}
