/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.domain.jpetstore;


import cn.emac.demo.domain.jpetstore.tables.Account;
import cn.emac.demo.domain.jpetstore.tables.Bannerdata;
import cn.emac.demo.domain.jpetstore.tables.Category;
import cn.emac.demo.domain.jpetstore.tables.Inventory;
import cn.emac.demo.domain.jpetstore.tables.Item;
import cn.emac.demo.domain.jpetstore.tables.Lineitem;
import cn.emac.demo.domain.jpetstore.tables.Orders;
import cn.emac.demo.domain.jpetstore.tables.Orderstatus;
import cn.emac.demo.domain.jpetstore.tables.Product;
import cn.emac.demo.domain.jpetstore.tables.Profile;
import cn.emac.demo.domain.jpetstore.tables.Sequence;
import cn.emac.demo.domain.jpetstore.tables.Signon;
import cn.emac.demo.domain.jpetstore.tables.Supplier;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jpetstore
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * Cadastro de Contas
	 */
	public static final Account ACCOUNT = cn.emac.demo.domain.jpetstore.tables.Account.ACCOUNT;

	/**
	 * Banner Data
	 */
	public static final Bannerdata BANNERDATA = cn.emac.demo.domain.jpetstore.tables.Bannerdata.BANNERDATA;

	/**
	 * Categorias
	 */
	public static final Category CATEGORY = cn.emac.demo.domain.jpetstore.tables.Category.CATEGORY;

	/**
	 * Inventory
	 */
	public static final Inventory INVENTORY = cn.emac.demo.domain.jpetstore.tables.Inventory.INVENTORY;

	/**
	 * Itens
	 */
	public static final Item ITEM = cn.emac.demo.domain.jpetstore.tables.Item.ITEM;

	/**
	 * Line Item
	 */
	public static final Lineitem LINEITEM = cn.emac.demo.domain.jpetstore.tables.Lineitem.LINEITEM;

	/**
	 * Cadastro de pedidos
	 */
	public static final Orders ORDERS = cn.emac.demo.domain.jpetstore.tables.Orders.ORDERS;

	/**
	 * Status de pedidos
	 */
	public static final Orderstatus ORDERSTATUS = cn.emac.demo.domain.jpetstore.tables.Orderstatus.ORDERSTATUS;

	/**
	 * Categorias
	 */
	public static final Product PRODUCT = cn.emac.demo.domain.jpetstore.tables.Product.PRODUCT;

	/**
	 * Cadastro de Perfis
	 */
	public static final Profile PROFILE = cn.emac.demo.domain.jpetstore.tables.Profile.PROFILE;

	/**
	 * Inventory
	 */
	public static final Sequence SEQUENCE = cn.emac.demo.domain.jpetstore.tables.Sequence.SEQUENCE;

	/**
	 * Cadastro de usuários
	 */
	public static final Signon SIGNON = cn.emac.demo.domain.jpetstore.tables.Signon.SIGNON;

	/**
	 * Cadastro de Fornecedores
	 */
	public static final Supplier SUPPLIER = cn.emac.demo.domain.jpetstore.tables.Supplier.SUPPLIER;
}
