/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain;


import cn.emac.demo.petstore.domain.tables.Account;
import cn.emac.demo.petstore.domain.tables.Bannerdata;
import cn.emac.demo.petstore.domain.tables.Category;
import cn.emac.demo.petstore.domain.tables.Inventory;
import cn.emac.demo.petstore.domain.tables.Item;
import cn.emac.demo.petstore.domain.tables.Lineitem;
import cn.emac.demo.petstore.domain.tables.Orders;
import cn.emac.demo.petstore.domain.tables.Orderstatus;
import cn.emac.demo.petstore.domain.tables.Product;
import cn.emac.demo.petstore.domain.tables.Profile;
import cn.emac.demo.petstore.domain.tables.Sequence;
import cn.emac.demo.petstore.domain.tables.Signon;
import cn.emac.demo.petstore.domain.tables.Supplier;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jpetstore extends SchemaImpl {

    private static final long serialVersionUID = -451691170;

    /**
     * The reference instance of <code>jpetstore</code>
     */
    public static final Jpetstore JPETSTORE = new Jpetstore();

    /**
     * Cadastro de Contas
     */
    public final Account ACCOUNT = cn.emac.demo.petstore.domain.tables.Account.ACCOUNT;

    /**
     * Banner Data
     */
    public final Bannerdata BANNERDATA = cn.emac.demo.petstore.domain.tables.Bannerdata.BANNERDATA;

    /**
     * Categorias
     */
    public final Category CATEGORY = cn.emac.demo.petstore.domain.tables.Category.CATEGORY;

    /**
     * Inventory
     */
    public final Inventory INVENTORY = cn.emac.demo.petstore.domain.tables.Inventory.INVENTORY;

    /**
     * Itens
     */
    public final Item ITEM = cn.emac.demo.petstore.domain.tables.Item.ITEM;

    /**
     * Line Item
     */
    public final Lineitem LINEITEM = cn.emac.demo.petstore.domain.tables.Lineitem.LINEITEM;

    /**
     * Cadastro de pedidos
     */
    public final Orders ORDERS = cn.emac.demo.petstore.domain.tables.Orders.ORDERS;

    /**
     * Status de pedidos
     */
    public final Orderstatus ORDERSTATUS = cn.emac.demo.petstore.domain.tables.Orderstatus.ORDERSTATUS;

    /**
     * Categorias
     */
    public final Product PRODUCT = cn.emac.demo.petstore.domain.tables.Product.PRODUCT;

    /**
     * Cadastro de Perfis
     */
    public final Profile PROFILE = cn.emac.demo.petstore.domain.tables.Profile.PROFILE;

    /**
     * Inventory
     */
    public final Sequence SEQUENCE = cn.emac.demo.petstore.domain.tables.Sequence.SEQUENCE;

    /**
     * Cadastro de usuários
     */
    public final Signon SIGNON = cn.emac.demo.petstore.domain.tables.Signon.SIGNON;

    /**
     * Cadastro de Fornecedores
     */
    public final Supplier SUPPLIER = cn.emac.demo.petstore.domain.tables.Supplier.SUPPLIER;

    /**
     * No further instances allowed
     */
    private Jpetstore() {
        super("jpetstore", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Bannerdata.BANNERDATA,
            Category.CATEGORY,
            Inventory.INVENTORY,
            Item.ITEM,
            Lineitem.LINEITEM,
            Orders.ORDERS,
            Orderstatus.ORDERSTATUS,
            Product.PRODUCT,
            Profile.PROFILE,
            Sequence.SEQUENCE,
            Signon.SIGNON,
            Supplier.SUPPLIER);
    }
}
