/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain;


import cn.emac.demo.petstore.domain.tables.*;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jpetstore extends SchemaImpl {

	private static final long serialVersionUID = -253830844;

	/**
	 * The reference instance of <code>jpetstore</code>
	 */
	public static final Jpetstore JPETSTORE = new Jpetstore();

	/**
	 * No further instances allowed
	 */
	private Jpetstore() {
		super("jpetstore");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Account.ACCOUNT,
			Bannerdata.BANNERDATA,
			Category.CATEGORY,
			Inventory.INVENTORY,
			Item.ITEM,
			Lineitem.LINEITEM,
			Orders.ORDERS,
			Orderstatus.ORDERSTATUS,
			Product.PRODUCT,
			Profile.PROFILE,
			Sequence.SEQUENCE,
			Signon.SIGNON,
			Supplier.SUPPLIER);
	}
}
