/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain;


import cn.emac.demo.petstore.domain.tables.Account;
import cn.emac.demo.petstore.domain.tables.Bannerdata;
import cn.emac.demo.petstore.domain.tables.Category;
import cn.emac.demo.petstore.domain.tables.Inventory;
import cn.emac.demo.petstore.domain.tables.Item;
import cn.emac.demo.petstore.domain.tables.Lineitem;
import cn.emac.demo.petstore.domain.tables.Orders;
import cn.emac.demo.petstore.domain.tables.Orderstatus;
import cn.emac.demo.petstore.domain.tables.Product;
import cn.emac.demo.petstore.domain.tables.Profile;
import cn.emac.demo.petstore.domain.tables.Sequence;
import cn.emac.demo.petstore.domain.tables.Signon;
import cn.emac.demo.petstore.domain.tables.Supplier;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jpetstore
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Cadastro de Contas
     */
    public static final Account ACCOUNT = cn.emac.demo.petstore.domain.tables.Account.ACCOUNT;

    /**
     * Banner Data
     */
    public static final Bannerdata BANNERDATA = cn.emac.demo.petstore.domain.tables.Bannerdata.BANNERDATA;

    /**
     * Categorias
     */
    public static final Category CATEGORY = cn.emac.demo.petstore.domain.tables.Category.CATEGORY;

    /**
     * Inventory
     */
    public static final Inventory INVENTORY = cn.emac.demo.petstore.domain.tables.Inventory.INVENTORY;

    /**
     * Itens
     */
    public static final Item ITEM = cn.emac.demo.petstore.domain.tables.Item.ITEM;

    /**
     * Line Item
     */
    public static final Lineitem LINEITEM = cn.emac.demo.petstore.domain.tables.Lineitem.LINEITEM;

    /**
     * Cadastro de pedidos
     */
    public static final Orders ORDERS = cn.emac.demo.petstore.domain.tables.Orders.ORDERS;

    /**
     * Status de pedidos
     */
    public static final Orderstatus ORDERSTATUS = cn.emac.demo.petstore.domain.tables.Orderstatus.ORDERSTATUS;

    /**
     * Categorias
     */
    public static final Product PRODUCT = cn.emac.demo.petstore.domain.tables.Product.PRODUCT;

    /**
     * Cadastro de Perfis
     */
    public static final Profile PROFILE = cn.emac.demo.petstore.domain.tables.Profile.PROFILE;

    /**
     * Inventory
     */
    public static final Sequence SEQUENCE = cn.emac.demo.petstore.domain.tables.Sequence.SEQUENCE;

    /**
     * Cadastro de usuários
     */
    public static final Signon SIGNON = cn.emac.demo.petstore.domain.tables.Signon.SIGNON;

    /**
     * Cadastro de Fornecedores
     */
    public static final Supplier SUPPLIER = cn.emac.demo.petstore.domain.tables.Supplier.SUPPLIER;
}
