/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.records;


import cn.emac.demo.petstore.domain.tables.Bannerdata;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Banner Data
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BannerdataRecord extends UpdatableRecordImpl<BannerdataRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1252708219;

    /**
     * Setter for <code>jpetstore.bannerdata.favcategory</code>.
     */
    public BannerdataRecord setFavcategory(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.bannerdata.favcategory</code>.
     */
    public String getFavcategory() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jpetstore.bannerdata.bannername</code>.
     */
    public BannerdataRecord setBannername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.bannerdata.bannername</code>.
     */
    public String getBannername() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Bannerdata.BANNERDATA.FAVCATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Bannerdata.BANNERDATA.BANNERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFavcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBannername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerdataRecord value1(String value) {
        setFavcategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerdataRecord value2(String value) {
        setBannername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerdataRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BannerdataRecord
     */
    public BannerdataRecord() {
        super(Bannerdata.BANNERDATA);
    }

    /**
     * Create a detached, initialised BannerdataRecord
     */
    public BannerdataRecord(String favcategory, String bannername) {
        super(Bannerdata.BANNERDATA);

        set(0, favcategory);
        set(1, bannername);
    }
}
