/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.records;


import cn.emac.demo.petstore.domain.tables.Orders;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Cadastro de pedidos
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = -1494396312;

    /**
     * Setter for <code>jpetstore.orders.orderid</code>.
     */
    public OrdersRecord setOrderid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.orderid</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jpetstore.orders.userid</code>.
     */
    public OrdersRecord setUserid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.userid</code>.
     */
    public String getUserid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jpetstore.orders.orderdate</code>.
     */
    public OrdersRecord setOrderdate(Date value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.orderdate</code>.
     */
    public Date getOrderdate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>jpetstore.orders.shipaddr1</code>.
     */
    public OrdersRecord setShipaddr1(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.shipaddr1</code>.
     */
    public String getShipaddr1() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jpetstore.orders.shipaddr2</code>.
     */
    public OrdersRecord setShipaddr2(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.shipaddr2</code>.
     */
    public String getShipaddr2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jpetstore.orders.shipcity</code>.
     */
    public OrdersRecord setShipcity(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.shipcity</code>.
     */
    public String getShipcity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jpetstore.orders.shipstate</code>.
     */
    public OrdersRecord setShipstate(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.shipstate</code>.
     */
    public String getShipstate() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jpetstore.orders.shipzip</code>.
     */
    public OrdersRecord setShipzip(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.shipzip</code>.
     */
    public String getShipzip() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jpetstore.orders.shipcountry</code>.
     */
    public OrdersRecord setShipcountry(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.shipcountry</code>.
     */
    public String getShipcountry() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jpetstore.orders.billaddr1</code>.
     */
    public OrdersRecord setBilladdr1(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.billaddr1</code>.
     */
    public String getBilladdr1() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jpetstore.orders.billaddr2</code>.
     */
    public OrdersRecord setBilladdr2(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.billaddr2</code>.
     */
    public String getBilladdr2() {
        return (String) get(10);
    }

    /**
     * Setter for <code>jpetstore.orders.billcity</code>.
     */
    public OrdersRecord setBillcity(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.billcity</code>.
     */
    public String getBillcity() {
        return (String) get(11);
    }

    /**
     * Setter for <code>jpetstore.orders.billstate</code>.
     */
    public OrdersRecord setBillstate(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.billstate</code>.
     */
    public String getBillstate() {
        return (String) get(12);
    }

    /**
     * Setter for <code>jpetstore.orders.billzip</code>.
     */
    public OrdersRecord setBillzip(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.billzip</code>.
     */
    public String getBillzip() {
        return (String) get(13);
    }

    /**
     * Setter for <code>jpetstore.orders.billcountry</code>.
     */
    public OrdersRecord setBillcountry(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.billcountry</code>.
     */
    public String getBillcountry() {
        return (String) get(14);
    }

    /**
     * Setter for <code>jpetstore.orders.courier</code>.
     */
    public OrdersRecord setCourier(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.courier</code>.
     */
    public String getCourier() {
        return (String) get(15);
    }

    /**
     * Setter for <code>jpetstore.orders.totalprice</code>.
     */
    public OrdersRecord setTotalprice(BigDecimal value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.totalprice</code>.
     */
    public BigDecimal getTotalprice() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>jpetstore.orders.billtofirstname</code>.
     */
    public OrdersRecord setBilltofirstname(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.billtofirstname</code>.
     */
    public String getBilltofirstname() {
        return (String) get(17);
    }

    /**
     * Setter for <code>jpetstore.orders.billtolastname</code>.
     */
    public OrdersRecord setBilltolastname(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.billtolastname</code>.
     */
    public String getBilltolastname() {
        return (String) get(18);
    }

    /**
     * Setter for <code>jpetstore.orders.shiptofirstname</code>.
     */
    public OrdersRecord setShiptofirstname(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.shiptofirstname</code>.
     */
    public String getShiptofirstname() {
        return (String) get(19);
    }

    /**
     * Setter for <code>jpetstore.orders.shiptolastname</code>.
     */
    public OrdersRecord setShiptolastname(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.shiptolastname</code>.
     */
    public String getShiptolastname() {
        return (String) get(20);
    }

    /**
     * Setter for <code>jpetstore.orders.creditcard</code>.
     */
    public OrdersRecord setCreditcard(String value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.creditcard</code>.
     */
    public String getCreditcard() {
        return (String) get(21);
    }

    /**
     * Setter for <code>jpetstore.orders.exprdate</code>.
     */
    public OrdersRecord setExprdate(String value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.exprdate</code>.
     */
    public String getExprdate() {
        return (String) get(22);
    }

    /**
     * Setter for <code>jpetstore.orders.cardtype</code>.
     */
    public OrdersRecord setCardtype(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.cardtype</code>.
     */
    public String getCardtype() {
        return (String) get(23);
    }

    /**
     * Setter for <code>jpetstore.orders.locale</code>.
     */
    public OrdersRecord setLocale(String value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.orders.locale</code>.
     */
    public String getLocale() {
        return (String) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer orderid, String userid, Date orderdate, String shipaddr1, String shipaddr2, String shipcity, String shipstate, String shipzip, String shipcountry, String billaddr1, String billaddr2, String billcity, String billstate, String billzip, String billcountry, String courier, BigDecimal totalprice, String billtofirstname, String billtolastname, String shiptofirstname, String shiptolastname, String creditcard, String exprdate, String cardtype, String locale) {
        super(Orders.ORDERS);

        set(0, orderid);
        set(1, userid);
        set(2, orderdate);
        set(3, shipaddr1);
        set(4, shipaddr2);
        set(5, shipcity);
        set(6, shipstate);
        set(7, shipzip);
        set(8, shipcountry);
        set(9, billaddr1);
        set(10, billaddr2);
        set(11, billcity);
        set(12, billstate);
        set(13, billzip);
        set(14, billcountry);
        set(15, courier);
        set(16, totalprice);
        set(17, billtofirstname);
        set(18, billtolastname);
        set(19, shiptofirstname);
        set(20, shiptolastname);
        set(21, creditcard);
        set(22, exprdate);
        set(23, cardtype);
        set(24, locale);
    }
}
