/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.records;


import cn.emac.demo.petstore.domain.tables.Profile;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Cadastro de Perfis
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileRecord extends UpdatableRecordImpl<ProfileRecord> implements Record5<String, String, String, Byte, Byte> {

    private static final long serialVersionUID = 1766689532;

    /**
     * Setter for <code>jpetstore.profile.userid</code>.
     */
    public ProfileRecord setUserid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.profile.userid</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jpetstore.profile.langpref</code>.
     */
    public ProfileRecord setLangpref(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.profile.langpref</code>.
     */
    public String getLangpref() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jpetstore.profile.favcategory</code>.
     */
    public ProfileRecord setFavcategory(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.profile.favcategory</code>.
     */
    public String getFavcategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jpetstore.profile.mylistopt</code>.
     */
    public ProfileRecord setMylistopt(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.profile.mylistopt</code>.
     */
    public Byte getMylistopt() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>jpetstore.profile.banneropt</code>.
     */
    public ProfileRecord setBanneropt(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.profile.banneropt</code>.
     */
    public Byte getBanneropt() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Byte, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Byte, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Profile.PROFILE.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Profile.PROFILE.LANGPREF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Profile.PROFILE.FAVCATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Profile.PROFILE.MYLISTOPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Profile.PROFILE.BANNEROPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLangpref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFavcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getMylistopt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getBanneropt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value1(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value2(String value) {
        setLangpref(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value3(String value) {
        setFavcategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value4(Byte value) {
        setMylistopt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value5(Byte value) {
        setBanneropt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord values(String value1, String value2, String value3, Byte value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfileRecord
     */
    public ProfileRecord() {
        super(Profile.PROFILE);
    }

    /**
     * Create a detached, initialised ProfileRecord
     */
    public ProfileRecord(String userid, String langpref, String favcategory, Byte mylistopt, Byte banneropt) {
        super(Profile.PROFILE);

        set(0, userid);
        set(1, langpref);
        set(2, favcategory);
        set(3, mylistopt);
        set(4, banneropt);
    }
}
