/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain.tables.records;


import cn.emac.demo.petstore.domain.tables.Sequence;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * Inventory
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SequenceRecord extends UpdatableRecordImpl<SequenceRecord> implements Record2<String, Integer> {

	private static final long serialVersionUID = -1163830439;

	/**
	 * Setter for <code>jpetstore.sequence.name</code>.
	 */
	public SequenceRecord setName(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>jpetstore.sequence.name</code>.
	 */
	public String getName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>jpetstore.sequence.nextid</code>.
	 */
	public SequenceRecord setNextid(Integer value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>jpetstore.sequence.nextid</code>.
	 */
	public Integer getNextid() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Sequence.SEQUENCE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Sequence.SEQUENCE.NEXTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNextid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SequenceRecord value1(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SequenceRecord value2(Integer value) {
		setNextid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SequenceRecord values(String value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SequenceRecord
	 */
	public SequenceRecord() {
		super(Sequence.SEQUENCE);
	}

	/**
	 * Create a detached, initialised SequenceRecord
	 */
	public SequenceRecord(String name, Integer nextid) {
		super(Sequence.SEQUENCE);

		setValue(0, name);
		setValue(1, nextid);
	}
}
