/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.records;


import cn.emac.demo.petstore.domain.tables.Supplier;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Cadastro de Fornecedores
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplierRecord extends UpdatableRecordImpl<SupplierRecord> implements Record9<Integer, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -447202708;

    /**
     * Setter for <code>jpetstore.supplier.suppid</code>.
     */
    public SupplierRecord setSuppid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.supplier.suppid</code>.
     */
    public Integer getSuppid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jpetstore.supplier.name</code>.
     */
    public SupplierRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.supplier.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jpetstore.supplier.status</code>.
     */
    public SupplierRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.supplier.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jpetstore.supplier.addr1</code>.
     */
    public SupplierRecord setAddr1(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.supplier.addr1</code>.
     */
    public String getAddr1() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jpetstore.supplier.addr2</code>.
     */
    public SupplierRecord setAddr2(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.supplier.addr2</code>.
     */
    public String getAddr2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jpetstore.supplier.city</code>.
     */
    public SupplierRecord setCity(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.supplier.city</code>.
     */
    public String getCity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jpetstore.supplier.state</code>.
     */
    public SupplierRecord setState(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.supplier.state</code>.
     */
    public String getState() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jpetstore.supplier.zip</code>.
     */
    public SupplierRecord setZip(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.supplier.zip</code>.
     */
    public String getZip() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jpetstore.supplier.phone</code>.
     */
    public SupplierRecord setPhone(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>jpetstore.supplier.phone</code>.
     */
    public String getPhone() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Supplier.SUPPLIER.SUPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Supplier.SUPPLIER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Supplier.SUPPLIER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Supplier.SUPPLIER.ADDR1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Supplier.SUPPLIER.ADDR2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Supplier.SUPPLIER.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Supplier.SUPPLIER.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Supplier.SUPPLIER.ZIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Supplier.SUPPLIER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSuppid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAddr1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAddr2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord value1(Integer value) {
        setSuppid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord value4(String value) {
        setAddr1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord value5(String value) {
        setAddr2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord value6(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord value7(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord value8(String value) {
        setZip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord value9(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SupplierRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplierRecord
     */
    public SupplierRecord() {
        super(Supplier.SUPPLIER);
    }

    /**
     * Create a detached, initialised SupplierRecord
     */
    public SupplierRecord(Integer suppid, String name, String status, String addr1, String addr2, String city, String state, String zip, String phone) {
        super(Supplier.SUPPLIER);

        set(0, suppid);
        set(1, name);
        set(2, status);
        set(3, addr1);
        set(4, addr2);
        set(5, city);
        set(6, state);
        set(7, zip);
        set(8, phone);
    }
}
