/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Cadastro de Contas
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = 874949719;

    private String userid;
    private String email;
    private String firstname;
    private String lastname;
    private String status;
    private String addr1;
    private String addr2;
    private String city;
    private String state;
    private String zip;
    private String country;
    private String phone;

    public Account() {}

    public Account(Account value) {
        this.userid = value.userid;
        this.email = value.email;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.status = value.status;
        this.addr1 = value.addr1;
        this.addr2 = value.addr2;
        this.city = value.city;
        this.state = value.state;
        this.zip = value.zip;
        this.country = value.country;
        this.phone = value.phone;
    }

    public Account(
        String userid,
        String email,
        String firstname,
        String lastname,
        String status,
        String addr1,
        String addr2,
        String city,
        String state,
        String zip,
        String country,
        String phone
    ) {
        this.userid = userid;
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.status = status;
        this.addr1 = addr1;
        this.addr2 = addr2;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.country = country;
        this.phone = phone;
    }

    public String getUserid() {
        return this.userid;
    }

    public Account setUserid(String userid) {
        this.userid = userid;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public Account setEmail(String email) {
        this.email = email;
        return this;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public Account setFirstname(String firstname) {
        this.firstname = firstname;
        return this;
    }

    public String getLastname() {
        return this.lastname;
    }

    public Account setLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public Account setStatus(String status) {
        this.status = status;
        return this;
    }

    public String getAddr1() {
        return this.addr1;
    }

    public Account setAddr1(String addr1) {
        this.addr1 = addr1;
        return this;
    }

    public String getAddr2() {
        return this.addr2;
    }

    public Account setAddr2(String addr2) {
        this.addr2 = addr2;
        return this;
    }

    public String getCity() {
        return this.city;
    }

    public Account setCity(String city) {
        this.city = city;
        return this;
    }

    public String getState() {
        return this.state;
    }

    public Account setState(String state) {
        this.state = state;
        return this;
    }

    public String getZip() {
        return this.zip;
    }

    public Account setZip(String zip) {
        this.zip = zip;
        return this;
    }

    public String getCountry() {
        return this.country;
    }

    public Account setCountry(String country) {
        this.country = country;
        return this;
    }

    public String getPhone() {
        return this.phone;
    }

    public Account setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(userid);
        sb.append(", ").append(email);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(status);
        sb.append(", ").append(addr1);
        sb.append(", ").append(addr2);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(zip);
        sb.append(", ").append(country);
        sb.append(", ").append(phone);

        sb.append(")");
        return sb.toString();
    }
}
