/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Categorias
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Category implements Serializable {

	private static final long serialVersionUID = -1047943058;

	private String catid;
	private String name;
	private String descn;

	public Category() {}

	public Category(Category value) {
		this.catid = value.catid;
		this.name = value.name;
		this.descn = value.descn;
	}

	public Category(
		String catid,
		String name,
		String descn
	) {
		this.catid = catid;
		this.name = name;
		this.descn = descn;
	}

	public String getCatid() {
		return this.catid;
	}

	public Category setCatid(String catid) {
		this.catid = catid;
		return this;
	}

	public String getName() {
		return this.name;
	}

	public Category setName(String name) {
		this.name = name;
		return this;
	}

	public String getDescn() {
		return this.descn;
	}

	public Category setDescn(String descn) {
		this.descn = descn;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Category (");

		sb.append(catid);
		sb.append(", ").append(name);
		sb.append(", ").append(descn);

		sb.append(")");
		return sb.toString();
	}
}
