/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * Line Item
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lineitem implements Serializable {

    private static final long serialVersionUID = 1312957928;

    private Integer    orderid;
    private Integer    linenum;
    private String     itemid;
    private Integer    quantity;
    private BigDecimal unitprice;

    public Lineitem() {}

    public Lineitem(Lineitem value) {
        this.orderid = value.orderid;
        this.linenum = value.linenum;
        this.itemid = value.itemid;
        this.quantity = value.quantity;
        this.unitprice = value.unitprice;
    }

    public Lineitem(
        Integer    orderid,
        Integer    linenum,
        String     itemid,
        Integer    quantity,
        BigDecimal unitprice
    ) {
        this.orderid = orderid;
        this.linenum = linenum;
        this.itemid = itemid;
        this.quantity = quantity;
        this.unitprice = unitprice;
    }

    public Integer getOrderid() {
        return this.orderid;
    }

    public Lineitem setOrderid(Integer orderid) {
        this.orderid = orderid;
        return this;
    }

    public Integer getLinenum() {
        return this.linenum;
    }

    public Lineitem setLinenum(Integer linenum) {
        this.linenum = linenum;
        return this;
    }

    public String getItemid() {
        return this.itemid;
    }

    public Lineitem setItemid(String itemid) {
        this.itemid = itemid;
        return this;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public Lineitem setQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    public BigDecimal getUnitprice() {
        return this.unitprice;
    }

    public Lineitem setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Lineitem (");

        sb.append(orderid);
        sb.append(", ").append(linenum);
        sb.append(", ").append(itemid);
        sb.append(", ").append(quantity);
        sb.append(", ").append(unitprice);

        sb.append(")");
        return sb.toString();
    }
}
