/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * Cadastro de pedidos
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders implements Serializable {

    private static final long serialVersionUID = -890104681;

    private Integer    orderid;
    private String     userid;
    private Date       orderdate;
    private String     shipaddr1;
    private String     shipaddr2;
    private String     shipcity;
    private String     shipstate;
    private String     shipzip;
    private String     shipcountry;
    private String     billaddr1;
    private String     billaddr2;
    private String     billcity;
    private String     billstate;
    private String     billzip;
    private String     billcountry;
    private String     courier;
    private BigDecimal totalprice;
    private String     billtofirstname;
    private String     billtolastname;
    private String     shiptofirstname;
    private String     shiptolastname;
    private String     creditcard;
    private String     exprdate;
    private String     cardtype;
    private String     locale;

    public Orders() {}

    public Orders(Orders value) {
        this.orderid = value.orderid;
        this.userid = value.userid;
        this.orderdate = value.orderdate;
        this.shipaddr1 = value.shipaddr1;
        this.shipaddr2 = value.shipaddr2;
        this.shipcity = value.shipcity;
        this.shipstate = value.shipstate;
        this.shipzip = value.shipzip;
        this.shipcountry = value.shipcountry;
        this.billaddr1 = value.billaddr1;
        this.billaddr2 = value.billaddr2;
        this.billcity = value.billcity;
        this.billstate = value.billstate;
        this.billzip = value.billzip;
        this.billcountry = value.billcountry;
        this.courier = value.courier;
        this.totalprice = value.totalprice;
        this.billtofirstname = value.billtofirstname;
        this.billtolastname = value.billtolastname;
        this.shiptofirstname = value.shiptofirstname;
        this.shiptolastname = value.shiptolastname;
        this.creditcard = value.creditcard;
        this.exprdate = value.exprdate;
        this.cardtype = value.cardtype;
        this.locale = value.locale;
    }

    public Orders(
        Integer    orderid,
        String     userid,
        Date       orderdate,
        String     shipaddr1,
        String     shipaddr2,
        String     shipcity,
        String     shipstate,
        String     shipzip,
        String     shipcountry,
        String     billaddr1,
        String     billaddr2,
        String     billcity,
        String     billstate,
        String     billzip,
        String     billcountry,
        String     courier,
        BigDecimal totalprice,
        String     billtofirstname,
        String     billtolastname,
        String     shiptofirstname,
        String     shiptolastname,
        String     creditcard,
        String     exprdate,
        String     cardtype,
        String     locale
    ) {
        this.orderid = orderid;
        this.userid = userid;
        this.orderdate = orderdate;
        this.shipaddr1 = shipaddr1;
        this.shipaddr2 = shipaddr2;
        this.shipcity = shipcity;
        this.shipstate = shipstate;
        this.shipzip = shipzip;
        this.shipcountry = shipcountry;
        this.billaddr1 = billaddr1;
        this.billaddr2 = billaddr2;
        this.billcity = billcity;
        this.billstate = billstate;
        this.billzip = billzip;
        this.billcountry = billcountry;
        this.courier = courier;
        this.totalprice = totalprice;
        this.billtofirstname = billtofirstname;
        this.billtolastname = billtolastname;
        this.shiptofirstname = shiptofirstname;
        this.shiptolastname = shiptolastname;
        this.creditcard = creditcard;
        this.exprdate = exprdate;
        this.cardtype = cardtype;
        this.locale = locale;
    }

    public Integer getOrderid() {
        return this.orderid;
    }

    public Orders setOrderid(Integer orderid) {
        this.orderid = orderid;
        return this;
    }

    public String getUserid() {
        return this.userid;
    }

    public Orders setUserid(String userid) {
        this.userid = userid;
        return this;
    }

    public Date getOrderdate() {
        return this.orderdate;
    }

    public Orders setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
        return this;
    }

    public String getShipaddr1() {
        return this.shipaddr1;
    }

    public Orders setShipaddr1(String shipaddr1) {
        this.shipaddr1 = shipaddr1;
        return this;
    }

    public String getShipaddr2() {
        return this.shipaddr2;
    }

    public Orders setShipaddr2(String shipaddr2) {
        this.shipaddr2 = shipaddr2;
        return this;
    }

    public String getShipcity() {
        return this.shipcity;
    }

    public Orders setShipcity(String shipcity) {
        this.shipcity = shipcity;
        return this;
    }

    public String getShipstate() {
        return this.shipstate;
    }

    public Orders setShipstate(String shipstate) {
        this.shipstate = shipstate;
        return this;
    }

    public String getShipzip() {
        return this.shipzip;
    }

    public Orders setShipzip(String shipzip) {
        this.shipzip = shipzip;
        return this;
    }

    public String getShipcountry() {
        return this.shipcountry;
    }

    public Orders setShipcountry(String shipcountry) {
        this.shipcountry = shipcountry;
        return this;
    }

    public String getBilladdr1() {
        return this.billaddr1;
    }

    public Orders setBilladdr1(String billaddr1) {
        this.billaddr1 = billaddr1;
        return this;
    }

    public String getBilladdr2() {
        return this.billaddr2;
    }

    public Orders setBilladdr2(String billaddr2) {
        this.billaddr2 = billaddr2;
        return this;
    }

    public String getBillcity() {
        return this.billcity;
    }

    public Orders setBillcity(String billcity) {
        this.billcity = billcity;
        return this;
    }

    public String getBillstate() {
        return this.billstate;
    }

    public Orders setBillstate(String billstate) {
        this.billstate = billstate;
        return this;
    }

    public String getBillzip() {
        return this.billzip;
    }

    public Orders setBillzip(String billzip) {
        this.billzip = billzip;
        return this;
    }

    public String getBillcountry() {
        return this.billcountry;
    }

    public Orders setBillcountry(String billcountry) {
        this.billcountry = billcountry;
        return this;
    }

    public String getCourier() {
        return this.courier;
    }

    public Orders setCourier(String courier) {
        this.courier = courier;
        return this;
    }

    public BigDecimal getTotalprice() {
        return this.totalprice;
    }

    public Orders setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
        return this;
    }

    public String getBilltofirstname() {
        return this.billtofirstname;
    }

    public Orders setBilltofirstname(String billtofirstname) {
        this.billtofirstname = billtofirstname;
        return this;
    }

    public String getBilltolastname() {
        return this.billtolastname;
    }

    public Orders setBilltolastname(String billtolastname) {
        this.billtolastname = billtolastname;
        return this;
    }

    public String getShiptofirstname() {
        return this.shiptofirstname;
    }

    public Orders setShiptofirstname(String shiptofirstname) {
        this.shiptofirstname = shiptofirstname;
        return this;
    }

    public String getShiptolastname() {
        return this.shiptolastname;
    }

    public Orders setShiptolastname(String shiptolastname) {
        this.shiptolastname = shiptolastname;
        return this;
    }

    public String getCreditcard() {
        return this.creditcard;
    }

    public Orders setCreditcard(String creditcard) {
        this.creditcard = creditcard;
        return this;
    }

    public String getExprdate() {
        return this.exprdate;
    }

    public Orders setExprdate(String exprdate) {
        this.exprdate = exprdate;
        return this;
    }

    public String getCardtype() {
        return this.cardtype;
    }

    public Orders setCardtype(String cardtype) {
        this.cardtype = cardtype;
        return this;
    }

    public String getLocale() {
        return this.locale;
    }

    public Orders setLocale(String locale) {
        this.locale = locale;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Orders (");

        sb.append(orderid);
        sb.append(", ").append(userid);
        sb.append(", ").append(orderdate);
        sb.append(", ").append(shipaddr1);
        sb.append(", ").append(shipaddr2);
        sb.append(", ").append(shipcity);
        sb.append(", ").append(shipstate);
        sb.append(", ").append(shipzip);
        sb.append(", ").append(shipcountry);
        sb.append(", ").append(billaddr1);
        sb.append(", ").append(billaddr2);
        sb.append(", ").append(billcity);
        sb.append(", ").append(billstate);
        sb.append(", ").append(billzip);
        sb.append(", ").append(billcountry);
        sb.append(", ").append(courier);
        sb.append(", ").append(totalprice);
        sb.append(", ").append(billtofirstname);
        sb.append(", ").append(billtolastname);
        sb.append(", ").append(shiptofirstname);
        sb.append(", ").append(shiptolastname);
        sb.append(", ").append(creditcard);
        sb.append(", ").append(exprdate);
        sb.append(", ").append(cardtype);
        sb.append(", ").append(locale);

        sb.append(")");
        return sb.toString();
    }
}
