/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Categorias
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product implements Serializable {

    private static final long serialVersionUID = -1525102453;

    private String productid;
    private String category;
    private String name;
    private String descn;

    public Product() {}

    public Product(Product value) {
        this.productid = value.productid;
        this.category = value.category;
        this.name = value.name;
        this.descn = value.descn;
    }

    public Product(
        String productid,
        String category,
        String name,
        String descn
    ) {
        this.productid = productid;
        this.category = category;
        this.name = name;
        this.descn = descn;
    }

    public String getProductid() {
        return this.productid;
    }

    public Product setProductid(String productid) {
        this.productid = productid;
        return this;
    }

    public String getCategory() {
        return this.category;
    }

    public Product setCategory(String category) {
        this.category = category;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Product setName(String name) {
        this.name = name;
        return this;
    }

    public String getDescn() {
        return this.descn;
    }

    public Product setDescn(String descn) {
        this.descn = descn;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product (");

        sb.append(productid);
        sb.append(", ").append(category);
        sb.append(", ").append(name);
        sb.append(", ").append(descn);

        sb.append(")");
        return sb.toString();
    }
}
