/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * Cadastro de Perfis
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profile implements Serializable {

	private static final long serialVersionUID = -655825901;

	private String userid;
	private String langpref;
	private String favcategory;
	private Byte   mylistopt;
	private Byte   banneropt;

	public Profile() {}

	public Profile(Profile value) {
		this.userid = value.userid;
		this.langpref = value.langpref;
		this.favcategory = value.favcategory;
		this.mylistopt = value.mylistopt;
		this.banneropt = value.banneropt;
	}

	public Profile(
		String userid,
		String langpref,
		String favcategory,
		Byte   mylistopt,
		Byte   banneropt
	) {
		this.userid = userid;
		this.langpref = langpref;
		this.favcategory = favcategory;
		this.mylistopt = mylistopt;
		this.banneropt = banneropt;
	}

	public String getUserid() {
		return this.userid;
	}

	public Profile setUserid(String userid) {
		this.userid = userid;
		return this;
	}

	public String getLangpref() {
		return this.langpref;
	}

	public Profile setLangpref(String langpref) {
		this.langpref = langpref;
		return this;
	}

	public String getFavcategory() {
		return this.favcategory;
	}

	public Profile setFavcategory(String favcategory) {
		this.favcategory = favcategory;
		return this;
	}

	public Byte getMylistopt() {
		return this.mylistopt;
	}

	public Profile setMylistopt(Byte mylistopt) {
		this.mylistopt = mylistopt;
		return this;
	}

	public Byte getBanneropt() {
		return this.banneropt;
	}

	public Profile setBanneropt(Byte banneropt) {
		this.banneropt = banneropt;
		return this;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Profile (");

		sb.append(userid);
		sb.append(", ").append(langpref);
		sb.append(", ").append(favcategory);
		sb.append(", ").append(mylistopt);
		sb.append(", ").append(banneropt);

		sb.append(")");
		return sb.toString();
	}
}
