/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Cadastro de usuários
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Signon implements Serializable {

    private static final long serialVersionUID = 1178921449;

    private String username;
    private String password;

    public Signon() {}

    public Signon(Signon value) {
        this.username = value.username;
        this.password = value.password;
    }

    public Signon(
        String username,
        String password
    ) {
        this.username = username;
        this.password = password;
    }

    public String getUsername() {
        return this.username;
    }

    public Signon setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public Signon setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Signon (");

        sb.append(username);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
