/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Cadastro de Fornecedores
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Supplier implements Serializable {

    private static final long serialVersionUID = 446415823;

    private Integer suppid;
    private String  name;
    private String  status;
    private String  addr1;
    private String  addr2;
    private String  city;
    private String  state;
    private String  zip;
    private String  phone;

    public Supplier() {}

    public Supplier(Supplier value) {
        this.suppid = value.suppid;
        this.name = value.name;
        this.status = value.status;
        this.addr1 = value.addr1;
        this.addr2 = value.addr2;
        this.city = value.city;
        this.state = value.state;
        this.zip = value.zip;
        this.phone = value.phone;
    }

    public Supplier(
        Integer suppid,
        String  name,
        String  status,
        String  addr1,
        String  addr2,
        String  city,
        String  state,
        String  zip,
        String  phone
    ) {
        this.suppid = suppid;
        this.name = name;
        this.status = status;
        this.addr1 = addr1;
        this.addr2 = addr2;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.phone = phone;
    }

    public Integer getSuppid() {
        return this.suppid;
    }

    public Supplier setSuppid(Integer suppid) {
        this.suppid = suppid;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Supplier setName(String name) {
        this.name = name;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public Supplier setStatus(String status) {
        this.status = status;
        return this;
    }

    public String getAddr1() {
        return this.addr1;
    }

    public Supplier setAddr1(String addr1) {
        this.addr1 = addr1;
        return this;
    }

    public String getAddr2() {
        return this.addr2;
    }

    public Supplier setAddr2(String addr2) {
        this.addr2 = addr2;
        return this;
    }

    public String getCity() {
        return this.city;
    }

    public Supplier setCity(String city) {
        this.city = city;
        return this;
    }

    public String getState() {
        return this.state;
    }

    public Supplier setState(String state) {
        this.state = state;
        return this;
    }

    public String getZip() {
        return this.zip;
    }

    public Supplier setZip(String zip) {
        this.zip = zip;
        return this;
    }

    public String getPhone() {
        return this.phone;
    }

    public Supplier setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Supplier (");

        sb.append(suppid);
        sb.append(", ").append(name);
        sb.append(", ").append(status);
        sb.append(", ").append(addr1);
        sb.append(", ").append(addr2);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(zip);
        sb.append(", ").append(phone);

        sb.append(")");
        return sb.toString();
    }
}
