/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.domain.jpetstore.tables.records;


import cn.emac.demo.domain.jpetstore.tables.Item;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Itens
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record11<String, String, BigDecimal, BigDecimal, Integer, String, String, String, String, String, String> {

	private static final long serialVersionUID = 99760348;

	/**
	 * Setter for <code>jpetstore.item.itemid</code>.
	 */
	public void setItemid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jpetstore.item.itemid</code>.
	 */
	public String getItemid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>jpetstore.item.productid</code>.
	 */
	public void setProductid(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jpetstore.item.productid</code>.
	 */
	public String getProductid() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>jpetstore.item.listprice</code>.
	 */
	public void setListprice(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jpetstore.item.listprice</code>.
	 */
	public BigDecimal getListprice() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>jpetstore.item.unitcost</code>.
	 */
	public void setUnitcost(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jpetstore.item.unitcost</code>.
	 */
	public BigDecimal getUnitcost() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>jpetstore.item.supplier</code>.
	 */
	public void setSupplier(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jpetstore.item.supplier</code>.
	 */
	public Integer getSupplier() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>jpetstore.item.status</code>.
	 */
	public void setStatus(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>jpetstore.item.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>jpetstore.item.attr1</code>.
	 */
	public void setAttr1(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>jpetstore.item.attr1</code>.
	 */
	public String getAttr1() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>jpetstore.item.attr2</code>.
	 */
	public void setAttr2(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>jpetstore.item.attr2</code>.
	 */
	public String getAttr2() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>jpetstore.item.attr3</code>.
	 */
	public void setAttr3(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>jpetstore.item.attr3</code>.
	 */
	public String getAttr3() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>jpetstore.item.attr4</code>.
	 */
	public void setAttr4(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>jpetstore.item.attr4</code>.
	 */
	public String getAttr4() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>jpetstore.item.attr5</code>.
	 */
	public void setAttr5(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>jpetstore.item.attr5</code>.
	 */
	public String getAttr5() {
		return (String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, BigDecimal, BigDecimal, Integer, String, String, String, String, String, String> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, BigDecimal, BigDecimal, Integer, String, String, String, String, String, String> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Item.ITEM.ITEMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Item.ITEM.PRODUCTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return Item.ITEM.LISTPRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return Item.ITEM.UNITCOST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Item.ITEM.SUPPLIER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Item.ITEM.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Item.ITEM.ATTR1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Item.ITEM.ATTR2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Item.ITEM.ATTR3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Item.ITEM.ATTR4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Item.ITEM.ATTR5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getItemid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getProductid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getListprice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getUnitcost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getSupplier();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getAttr1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getAttr2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getAttr3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getAttr4();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getAttr5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value1(String value) {
		setItemid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value2(String value) {
		setProductid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value3(BigDecimal value) {
		setListprice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value4(BigDecimal value) {
		setUnitcost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value5(Integer value) {
		setSupplier(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value6(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value7(String value) {
		setAttr1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value8(String value) {
		setAttr2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value9(String value) {
		setAttr3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value10(String value) {
		setAttr4(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value11(String value) {
		setAttr5(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord values(String value1, String value2, BigDecimal value3, BigDecimal value4, Integer value5, String value6, String value7, String value8, String value9, String value10, String value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ItemRecord
	 */
	public ItemRecord() {
		super(Item.ITEM);
	}

	/**
	 * Create a detached, initialised ItemRecord
	 */
	public ItemRecord(String itemid, String productid, BigDecimal listprice, BigDecimal unitcost, Integer supplier, String status, String attr1, String attr2, String attr3, String attr4, String attr5) {
		super(Item.ITEM);

		setValue(0, itemid);
		setValue(1, productid);
		setValue(2, listprice);
		setValue(3, unitcost);
		setValue(4, supplier);
		setValue(5, status);
		setValue(6, attr1);
		setValue(7, attr2);
		setValue(8, attr3);
		setValue(9, attr4);
		setValue(10, attr5);
	}
}
