/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.domain.jpetstore.tables.records;


import cn.emac.demo.domain.jpetstore.tables.Profile;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Cadastro de Perfis
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileRecord extends UpdatableRecordImpl<ProfileRecord> implements Record5<String, String, String, Byte, Byte> {

	private static final long serialVersionUID = -896170846;

	/**
	 * Setter for <code>jpetstore.profile.userid</code>.
	 */
	public void setUserid(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jpetstore.profile.userid</code>.
	 */
	public String getUserid() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>jpetstore.profile.langpref</code>.
	 */
	public void setLangpref(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jpetstore.profile.langpref</code>.
	 */
	public String getLangpref() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>jpetstore.profile.favcategory</code>.
	 */
	public void setFavcategory(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jpetstore.profile.favcategory</code>.
	 */
	public String getFavcategory() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>jpetstore.profile.mylistopt</code>.
	 */
	public void setMylistopt(Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jpetstore.profile.mylistopt</code>.
	 */
	public Byte getMylistopt() {
		return (Byte) getValue(3);
	}

	/**
	 * Setter for <code>jpetstore.profile.banneropt</code>.
	 */
	public void setBanneropt(Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jpetstore.profile.banneropt</code>.
	 */
	public Byte getBanneropt() {
		return (Byte) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, Byte, Byte> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, String, Byte, Byte> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Profile.PROFILE.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Profile.PROFILE.LANGPREF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Profile.PROFILE.FAVCATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field4() {
		return Profile.PROFILE.MYLISTOPT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field5() {
		return Profile.PROFILE.BANNEROPT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getLangpref();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getFavcategory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value4() {
		return getMylistopt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value5() {
		return getBanneropt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileRecord value1(String value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileRecord value2(String value) {
		setLangpref(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileRecord value3(String value) {
		setFavcategory(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileRecord value4(Byte value) {
		setMylistopt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileRecord value5(Byte value) {
		setBanneropt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileRecord values(String value1, String value2, String value3, Byte value4, Byte value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProfileRecord
	 */
	public ProfileRecord() {
		super(Profile.PROFILE);
	}

	/**
	 * Create a detached, initialised ProfileRecord
	 */
	public ProfileRecord(String userid, String langpref, String favcategory, Byte mylistopt, Byte banneropt) {
		super(Profile.PROFILE);

		setValue(0, userid);
		setValue(1, langpref);
		setValue(2, favcategory);
		setValue(3, mylistopt);
		setValue(4, banneropt);
	}
}
