/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.daos;


import cn.emac.demo.petstore.domain.tables.Lineitem;
import cn.emac.demo.petstore.domain.tables.records.LineitemRecord;

import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * Line Item
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class LineitemDao extends DAOImpl<LineitemRecord, cn.emac.demo.petstore.domain.tables.pojos.Lineitem, Record2<Integer, Integer>> {

    /**
     * Create a new LineitemDao without any configuration
     */
    public LineitemDao() {
        super(Lineitem.LINEITEM, cn.emac.demo.petstore.domain.tables.pojos.Lineitem.class);
    }

    /**
     * Create a new LineitemDao with an attached configuration
     */
    @Autowired
    public LineitemDao(Configuration configuration) {
        super(Lineitem.LINEITEM, cn.emac.demo.petstore.domain.tables.pojos.Lineitem.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(cn.emac.demo.petstore.domain.tables.pojos.Lineitem object) {
        return compositeKeyRecord(object.getOrderid(), object.getLinenum());
    }

    /**
     * Fetch records that have <code>orderid IN (values)</code>
     */
    public List<cn.emac.demo.petstore.domain.tables.pojos.Lineitem> fetchByOrderid(Integer... values) {
        return fetch(Lineitem.LINEITEM.ORDERID, values);
    }

    /**
     * Fetch records that have <code>linenum IN (values)</code>
     */
    public List<cn.emac.demo.petstore.domain.tables.pojos.Lineitem> fetchByLinenum(Integer... values) {
        return fetch(Lineitem.LINEITEM.LINENUM, values);
    }

    /**
     * Fetch records that have <code>itemid IN (values)</code>
     */
    public List<cn.emac.demo.petstore.domain.tables.pojos.Lineitem> fetchByItemid(String... values) {
        return fetch(Lineitem.LINEITEM.ITEMID, values);
    }

    /**
     * Fetch records that have <code>quantity IN (values)</code>
     */
    public List<cn.emac.demo.petstore.domain.tables.pojos.Lineitem> fetchByQuantity(Integer... values) {
        return fetch(Lineitem.LINEITEM.QUANTITY, values);
    }

    /**
     * Fetch records that have <code>unitprice IN (values)</code>
     */
    public List<cn.emac.demo.petstore.domain.tables.pojos.Lineitem> fetchByUnitprice(BigDecimal... values) {
        return fetch(Lineitem.LINEITEM.UNITPRICE, values);
    }
}
