/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain.tables.daos;


import cn.emac.demo.petstore.domain.tables.Orders;
import cn.emac.demo.petstore.domain.tables.records.OrdersRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;


/**
 * Cadastro de pedidos
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class OrdersDao extends DAOImpl<OrdersRecord, cn.emac.demo.petstore.domain.tables.pojos.Orders, Integer> {

	/**
	 * Create a new OrdersDao without any configuration
	 */
	public OrdersDao() {
		super(Orders.ORDERS, cn.emac.demo.petstore.domain.tables.pojos.Orders.class);
	}

	/**
	 * Create a new OrdersDao with an attached configuration
	 */
	@Autowired
	public OrdersDao(Configuration configuration) {
		super(Orders.ORDERS, cn.emac.demo.petstore.domain.tables.pojos.Orders.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(cn.emac.demo.petstore.domain.tables.pojos.Orders object) {
		return object.getOrderid();
	}

	/**
	 * Fetch records that have <code>orderid IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByOrderid(Integer... values) {
		return fetch(Orders.ORDERS.ORDERID, values);
	}

	/**
	 * Fetch a unique record that has <code>orderid = value</code>
	 */
	public cn.emac.demo.petstore.domain.tables.pojos.Orders fetchOneByOrderid(Integer value) {
		return fetchOne(Orders.ORDERS.ORDERID, value);
	}

	/**
	 * Fetch records that have <code>userid IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByUserid(String... values) {
		return fetch(Orders.ORDERS.USERID, values);
	}

	/**
	 * Fetch records that have <code>orderdate IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByOrderdate(Date... values) {
		return fetch(Orders.ORDERS.ORDERDATE, values);
	}

	/**
	 * Fetch records that have <code>shipaddr1 IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByShipaddr1(String... values) {
		return fetch(Orders.ORDERS.SHIPADDR1, values);
	}

	/**
	 * Fetch records that have <code>shipaddr2 IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByShipaddr2(String... values) {
		return fetch(Orders.ORDERS.SHIPADDR2, values);
	}

	/**
	 * Fetch records that have <code>shipcity IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByShipcity(String... values) {
		return fetch(Orders.ORDERS.SHIPCITY, values);
	}

	/**
	 * Fetch records that have <code>shipstate IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByShipstate(String... values) {
		return fetch(Orders.ORDERS.SHIPSTATE, values);
	}

	/**
	 * Fetch records that have <code>shipzip IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByShipzip(String... values) {
		return fetch(Orders.ORDERS.SHIPZIP, values);
	}

	/**
	 * Fetch records that have <code>shipcountry IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByShipcountry(String... values) {
		return fetch(Orders.ORDERS.SHIPCOUNTRY, values);
	}

	/**
	 * Fetch records that have <code>billaddr1 IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByBilladdr1(String... values) {
		return fetch(Orders.ORDERS.BILLADDR1, values);
	}

	/**
	 * Fetch records that have <code>billaddr2 IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByBilladdr2(String... values) {
		return fetch(Orders.ORDERS.BILLADDR2, values);
	}

	/**
	 * Fetch records that have <code>billcity IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByBillcity(String... values) {
		return fetch(Orders.ORDERS.BILLCITY, values);
	}

	/**
	 * Fetch records that have <code>billstate IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByBillstate(String... values) {
		return fetch(Orders.ORDERS.BILLSTATE, values);
	}

	/**
	 * Fetch records that have <code>billzip IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByBillzip(String... values) {
		return fetch(Orders.ORDERS.BILLZIP, values);
	}

	/**
	 * Fetch records that have <code>billcountry IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByBillcountry(String... values) {
		return fetch(Orders.ORDERS.BILLCOUNTRY, values);
	}

	/**
	 * Fetch records that have <code>courier IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByCourier(String... values) {
		return fetch(Orders.ORDERS.COURIER, values);
	}

	/**
	 * Fetch records that have <code>totalprice IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByTotalprice(BigDecimal... values) {
		return fetch(Orders.ORDERS.TOTALPRICE, values);
	}

	/**
	 * Fetch records that have <code>billtofirstname IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByBilltofirstname(String... values) {
		return fetch(Orders.ORDERS.BILLTOFIRSTNAME, values);
	}

	/**
	 * Fetch records that have <code>billtolastname IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByBilltolastname(String... values) {
		return fetch(Orders.ORDERS.BILLTOLASTNAME, values);
	}

	/**
	 * Fetch records that have <code>shiptofirstname IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByShiptofirstname(String... values) {
		return fetch(Orders.ORDERS.SHIPTOFIRSTNAME, values);
	}

	/**
	 * Fetch records that have <code>shiptolastname IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByShiptolastname(String... values) {
		return fetch(Orders.ORDERS.SHIPTOLASTNAME, values);
	}

	/**
	 * Fetch records that have <code>creditcard IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByCreditcard(String... values) {
		return fetch(Orders.ORDERS.CREDITCARD, values);
	}

	/**
	 * Fetch records that have <code>exprdate IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByExprdate(String... values) {
		return fetch(Orders.ORDERS.EXPRDATE, values);
	}

	/**
	 * Fetch records that have <code>cardtype IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByCardtype(String... values) {
		return fetch(Orders.ORDERS.CARDTYPE, values);
	}

	/**
	 * Fetch records that have <code>locale IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Orders> fetchByLocale(String... values) {
		return fetch(Orders.ORDERS.LOCALE, values);
	}
}
