/*
 * This file is generated by jOOQ.
*/
package cn.emac.demo.petstore.domain.tables.daos;


import cn.emac.demo.petstore.domain.tables.Orderstatus;
import cn.emac.demo.petstore.domain.tables.records.OrderstatusRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * Status de pedidos
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class OrderstatusDao extends DAOImpl<OrderstatusRecord, cn.emac.demo.petstore.domain.tables.pojos.Orderstatus, Record2<Integer, Integer>> {

    /**
     * Create a new OrderstatusDao without any configuration
     */
    public OrderstatusDao() {
        super(Orderstatus.ORDERSTATUS, cn.emac.demo.petstore.domain.tables.pojos.Orderstatus.class);
    }

    /**
     * Create a new OrderstatusDao with an attached configuration
     */
    @Autowired
    public OrderstatusDao(Configuration configuration) {
        super(Orderstatus.ORDERSTATUS, cn.emac.demo.petstore.domain.tables.pojos.Orderstatus.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(cn.emac.demo.petstore.domain.tables.pojos.Orderstatus object) {
        return compositeKeyRecord(object.getOrderid(), object.getLinenum());
    }

    /**
     * Fetch records that have <code>orderid IN (values)</code>
     */
    public List<cn.emac.demo.petstore.domain.tables.pojos.Orderstatus> fetchByOrderid(Integer... values) {
        return fetch(Orderstatus.ORDERSTATUS.ORDERID, values);
    }

    /**
     * Fetch records that have <code>linenum IN (values)</code>
     */
    public List<cn.emac.demo.petstore.domain.tables.pojos.Orderstatus> fetchByLinenum(Integer... values) {
        return fetch(Orderstatus.ORDERSTATUS.LINENUM, values);
    }

    /**
     * Fetch records that have <code>timestamp IN (values)</code>
     */
    public List<cn.emac.demo.petstore.domain.tables.pojos.Orderstatus> fetchByTimestamp(Date... values) {
        return fetch(Orderstatus.ORDERSTATUS.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<cn.emac.demo.petstore.domain.tables.pojos.Orderstatus> fetchByStatus(String... values) {
        return fetch(Orderstatus.ORDERSTATUS.STATUS, values);
    }
}
