/**
 * This class is generated by jOOQ
 */
package cn.emac.demo.petstore.domain.tables.daos;


import cn.emac.demo.petstore.domain.tables.Profile;
import cn.emac.demo.petstore.domain.tables.records.ProfileRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.util.List;


/**
 * Cadastro de Perfis
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ProfileDao extends DAOImpl<ProfileRecord, cn.emac.demo.petstore.domain.tables.pojos.Profile, String> {

	/**
	 * Create a new ProfileDao without any configuration
	 */
	public ProfileDao() {
		super(Profile.PROFILE, cn.emac.demo.petstore.domain.tables.pojos.Profile.class);
	}

	/**
	 * Create a new ProfileDao with an attached configuration
	 */
	@Autowired
	public ProfileDao(Configuration configuration) {
		super(Profile.PROFILE, cn.emac.demo.petstore.domain.tables.pojos.Profile.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected String getId(cn.emac.demo.petstore.domain.tables.pojos.Profile object) {
		return object.getUserid();
	}

	/**
	 * Fetch records that have <code>userid IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Profile> fetchByUserid(String... values) {
		return fetch(Profile.PROFILE.USERID, values);
	}

	/**
	 * Fetch a unique record that has <code>userid = value</code>
	 */
	public cn.emac.demo.petstore.domain.tables.pojos.Profile fetchOneByUserid(String value) {
		return fetchOne(Profile.PROFILE.USERID, value);
	}

	/**
	 * Fetch records that have <code>langpref IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Profile> fetchByLangpref(String... values) {
		return fetch(Profile.PROFILE.LANGPREF, values);
	}

	/**
	 * Fetch records that have <code>favcategory IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Profile> fetchByFavcategory(String... values) {
		return fetch(Profile.PROFILE.FAVCATEGORY, values);
	}

	/**
	 * Fetch records that have <code>mylistopt IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Profile> fetchByMylistopt(Byte... values) {
		return fetch(Profile.PROFILE.MYLISTOPT, values);
	}

	/**
	 * Fetch records that have <code>banneropt IN (values)</code>
	 */
	public List<cn.emac.demo.petstore.domain.tables.pojos.Profile> fetchByBanneropt(Byte... values) {
		return fetch(Profile.PROFILE.BANNEROPT, values);
	}
}
